{
 "title": "Saturn Node Details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "saturn_node_id", "label": "Node ID", "query": { "query": "label_values(id)" } }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "saturn_node_info{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "saturn_node_cpu_number{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "saturn_node_memory_total_kilobytes{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "saturn_node_disk_total_megabytes{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "saturn_node_sent_bytes_total{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "saturn_node_received_bytes_total{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "saturn_node_info{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "saturn_node_last_registration_timestamp{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "saturn_node_creation_timestamp{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(saturn_node_health_check_failures{id=\"$saturn_node_id\"}) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "saturn_node_cpu_load_avg{id=\"$saturn_node_id\"} / saturn_node_cpu_number{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(saturn_node_memory_total_kilobytes{id=\"$saturn_node_id\"} - saturn_node_memory_available_kilobytes{id=\"$saturn_node_id\"}) / saturn_node_memory_total_kilobytes{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "saturn_node_disk_available_megabytes{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "saturn_node_bias{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(saturn_node_sent_bytes_total{id=\"$saturn_node_id\"}[15m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(saturn_node_received_bytes_total{id=\"$saturn_node_id\"}[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TTFB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "saturn_node_response_duration_milliseconds{id=\"$saturn_node_id\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}