{
 "title": "Saturn Node Details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "saturn_node_id", "label": "Node ID", "query": { "query": "label_values(id)" } }
  ]
 },
 "panels": [
  { "title": "Summary and Hardware Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "saturn_node_info{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "saturn_node_cpu_number{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "saturn_node_memory_total_kilobytes{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "saturn_node_disk_total_megabytes{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "saturn_node_sent_bytes_total{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "saturn_node_received_bytes_total{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "saturn_node_info{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "saturn_node_last_registration_timestamp{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "saturn_node_creation_timestamp{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(saturn_node_health_check_failures{id=\"$saturn_node_id\"}) by (id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "saturn_node_version{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "saturn_node_cpu_load_avg{id=\"$saturn_node_id\"} / saturn_node_cpu_number{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(saturn_node_memory_total_kilobytes{id=\"$saturn_node_id\"} - saturn_node_memory_available_kilobytes{id=\"$saturn_node_id\"}) / saturn_node_memory_total_kilobytes{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Available",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "saturn_node_disk_available_megabytes{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Estimated Earnings and Weight", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Approximate Estimated Earnings",
   "type": "barchart",
   "description": "**Data may not be accurate.** For the source of truth, check the [official dashboard](https://dashboard.saturn.tech/address).",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "FIL" } },
   "targets": [
    {
     "expr": "increase(saturn_node_estimated_earnings_fil_total{id=\"$saturn_node_id\"}[$__rate_interval])",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Weight",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "saturn_node_bias{id=\"$saturn_node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Approximate Bandwidth Served",
   "type": "barchart",
   "description": "**Data may not be accurate.** For the source of truth, check the [official dashboard](https://dashboard.saturn.tech/address).",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(saturn_node_bandwidth_served_bytes_total{id=\"$saturn_node_id\"}[$__rate_interval])",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Approximate Retrievals",
   "type": "barchart",
   "description": "**Data may not be accurate.** For the source of truth, check the [official dashboard](https://dashboard.saturn.tech/address).",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(saturn_node_retrievals_total{id=\"$saturn_node_id\"}[$__rate_interval])",
     "legendFormat": "Value"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Time to First Byte",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "saturn_node_response_duration_milliseconds{id=\"$saturn_node_id\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "saturn_node_requests{id=\"$saturn_node_id\"}",
     "legendFormat": "error {{error}} cache {{cache}}"
    },
    {
     "expr": "saturn_node_requests{cache=\"true\", id=\"$saturn_node_id\"} / on (id) sum(saturn_node_requests{error=\"false\", id=\"$saturn_node_id\"}) by (id)",
     "legendFormat": "Cache Hit Ratio"
    },
    {
     "expr": "saturn_node_requests{error=\"true\", id=\"$saturn_node_id\"} / on (id) sum(saturn_node_requests{id=\"$saturn_node_id\"}) by (id)",
     "legendFormat": "Error Ratio"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(saturn_node_sent_bytes_total{id=\"$saturn_node_id\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(saturn_node_received_bytes_total{id=\"$saturn_node_id\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}